#include <stdint.h>
#include "../inc/tm4c123gh6pm.h"
#include "../inc/DAC.h"

void DAC_Init(void){
    SYSCTL_RCGCPWM_R |= SYSCTL_RCGCPWM_R0;
    SYSCTL_RCGCGPIO_R |= SYSCTL_RCGCGPIO_R4;
    GPIO_PORTE_LOCK_R = 0x4C4F434B;
    GPIO_PORTE_CR_R |= 0x20;
    GPIO_PORTE_DIR_R |= 0x20;
    GPIO_PORTE_DEN_R |= 0x20;
    GPIO_PORTE_AMSEL_R &= ~0x20;
    GPIO_PORTE_AFSEL_R |= 0x20;
    GPIO_PORTE_PCTL_R |= GPIO_PCTL_PE5_M0PWM5;
    SYSCTL_RCC_R &= ~SYSCTL_RCC_USEPWMDIV;
    PWM0_2_CTL_R |= PWM_2_CTL_DBCTLUPD_I;
    PWM0_2_GENA_R &= PWM_2_GENA_ACTCMPBD_NONE;
    PWM0_2_GENB_R |= (PWM_2_GENB_ACTCMPBD_ZERO | PWM_2_GENB_ACTLOAD_ONE);
    PWM0_2_LOAD_R = (256 - 1);
    PWM0_2_CMPB_R = 128;
    PWM0_2_CTL_R |= PWM_2_CTL_ENABLE;
    PWM0_INVERT_R |= PWM_INVERT_PWM5INV;
    PWM0_ENABLE_R |= PWM_ENABLE_PWM5EN;
}

void DAC_Out(uint32_t data){
    PWM0_2_CMPB_R = data;
}
